name: publish website

on:
  push:
    branches:
    - main

jobs:
  build:
    environment: site-deployment
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.9
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: build website
      #   run: pelican content -s pelicanconf.py -t ./themes/notmyidea/

      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          # aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_key_id: "some_key_id"
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'output'
          destination_dir: ''
